### PR TITLE
Added guide to the Single Topics section on authorization frameworks

### PR DESCRIPTION
**Pull request by LisaDziuba**
---- 

By submitting this pull request, I promise that:

- [x] I have read the [contribution guidelines](https://github.com/micromata/awesome-javascript-learning/blob/master/.github/contributing.md) thoroughly.
- [x] I ensure my submission follows each and every point.

### CODE REVIEW

**Comment by LisaDziuba** [comment]
Thanks for considering my PR. This guide covers everything authorization and comparison of authorization frameworks.

**Comment by octavian-nita** [comment]
Hi @LisaDziuba. I apologize, but I don't see any relationship between the article you suggest and JavaScript...

**Comment by LisaDziuba** [comment]
@octavian-nita, I'm sorry! If it's not a fit, just ignore my PR 🙌

**Comment by mischah** [comment]
Thanks @octavian-nita

**Pull request closed without merging**
