### PR TITLE
Add Paqmind.com | Interactive Learning

### PR DESCRIPTION
**Pull request by ivan-kleshnin**
Hi, Michael. Can I suggest you to check (and possibly add) a new platform we're currently developing: [paqmind.com](http://paqmind.com)

It's kinda "freeCodeCamp" / "KhanAcademy" inspired alternative. There's a lot of valuable unique free content already (and we update almost daily). But we don't have budget for marketing so I'd like more people to find it via GitHub and awesome list like yours ;)

The platform uses JavaScript as a main language.

### CODE REVIEW

**Comment by ivan-kleshnin** [comment]
I dunno why Travis disallows trailing slashes. This is just stupid :(

**Comment by mischah** [comment]
> I dunno why Travis disallows trailing slashes. 

It's a linting rule aiming to prevent duplicated entries.


> This is just stupid :(

Nah, it's a linting rule ;)

**Comment by ivan-kleshnin** [comment]
Oh, I see. Fixed that slash.

**Comment by mischah** [comment]
Thanks for the contribution. 
I’m pretty sure this will be an awesome ressource. But it seems not te be ready to be featured here in my humble opionion.

Keep up the good work.

**Comment by ivan-kleshnin** [comment]
@mischah no problem. I will make a new PR next year ;)

**Comment by mischah** [comment]
👍🏼

**Pull request closed without merging**
